### ISSUE TITLE
if (this.date.time === '') {

### ISSUE THREAD

**Issue by zzzgit** [bajian/vue-tab#1]
`if (this.date.time === '') {`
這行代碼報錯

Uncaught TypeError: Cannot read property 'time' of undefined

用的版本是1.2.0

**Comment by bajian** [comment]
1、本组件已升级Vue2.0，vue1.x自行修改“vue-tab.vue1.0”为“vue-tab.vue”即可，然后替换下style部分（兼容UC）即可
2、本组件并没有这行代码，这代码是您自己写的吗？

**Comment by zzzgit** [comment]
函數showCheck的第一行代碼
webpack編譯後的代碼

**Comment by zzzgit** [comment]
發錯地方了
